### PR TITLE
Updated workflow-issues.md to refer to key deletion

### PR DESCRIPTION
**Pull request by VRService**
Due to the unsupported behavior of the ``delete`` operator in roblox-ts to delete keys, it should be better documented for new learners that the roblox-ts equivalent is ``myArray[key] = undefined!;``

Reason for addition: I spent a good 20 minutes scraping through the discord to try and find the supported method of key deletion.

(Please refer to https://github.com/roblox-ts/roblox-ts/issues/547 for more information)

### CODE REVIEW

**Comment by Validark** [comment]
Looks good to me! @evaera

**Comment by evaera** [comment]
Is this really a workflow issue? I think it might fit better under unsupported features with a more succinct summary.

**Comment by Validark** [comment]
Yeah, that would probably be a better categorization.

**Comment by VRService** [comment]
Will update the PR!

**Comment by osyrisrblx** [comment]
FWIW, `myArray[key] = undefined!;` is bad practice. You should never do that.

If your array is of type `Array<number>`, indices `0` to `.size() - 1` should all be numbers.
- If you want to remove the last element use `myArray.pop()`.
- If you want to remove the first element use `myArray.shift()`.
- If you want to remove a specific element use `myArray.remove(i)`. This will shift all of the other indices down.

If you want to delete a key from an object, make sure the type of the field is undefine-able. If it isn't, and you're setting it to defined like you described you are lying to the type system.
When it comes to the type system: garbage in, garbage out.

Otherwise, you should use a Map<K, V> object with `map.delete(key)`.

**Comment by VRService** [comment]
Done this! Please read updated PR.

**Comment by VRService** [comment]
> FWIW, `myArray[key] = undefined!;` is bad practice. You should never do that.
> 
> If your array is of type `Array<T>`, indices `0` to `.size() - 1` should all be `T`.
> 
> * If you want to remove the last element use `myArray.pop()`.
> * If you want to remove the first element use `myArray.shift()`.
> * If you want to remove a specific element use `myArray.remove(i)`. This will shift all of the other indices down.
> 
> If you want to delete a key from an object, make sure the type of the field is undefine-able. If it isn't, and you're setting it to defined like you described you are lying to the type system.
> When it comes to the type system: garbage in, garbage out.
> 
> Otherwise, you should use a Map<K, V> object with `map.delete(key)`.

Right, just read this.
Unfortunately this doesn't seem to work for my use case, which can't be defined as Array<T> - it wants to register as a non-Lua dictionary. If you want I can send in my code to you.

For my use case though, when not using the Array type (and hence no remove) it's only possible to use myDictionary[key] = undefined!;

**Comment by VRService** [comment]
@osyrisrblx I've updated for a Map hyperlink instead.

**Comment by evaera** [comment]
Actually, can we link to https://roblox-ts.github.io/types/interfaces/_es_d_.map.html instead?

**Comment by VRService** [comment]
@evaera Done!

**Pull request merged**
